### ISSUE TITLE
失败了

### ISSUE THREAD

**Issue by jonny77** [robotJie/mdns_reflector_go#2]
dns-sd -B _hap._tcp 

23:06:04.795  Add        3  30 local.               _hap._tcp.           HASS Bridge 1701D4
23:06:04.795  Add        2  30 local.               _hap._tcp.           HASS Bridge 4057B2

30: bridge100: <UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 status UP

ip link show

30: bridge100: <UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 status UP
    link/ether d2:11:e5:97:49:64 brd ff:ff:ff:ff:ff:ff

wifi是en1，
对应的刚好是
./mdns_reflector_arm64 -ifaces=en1,bridge100
然后启动docker ，进入ha。
配置好homekit后，出现二维码，扫描后提示未认证配件（之前是这个都不出来）点击仍然添加后，后面还是失败了
以下是我的compose文件

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

**Comment by laris** [comment]
我这里看起来反射也没有反应
update：看起来ios HomeKit可以扫码添加了，反射还是现实32，奇怪

```
dns-sd -B _hap._tcp
Browsing for _hap._tcp
DATE: ---Wed 02 Apr 2025---
21:33:13.414  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
21:33:13.416  Add        2  32 local.               _hap._tcp.           HASS Bridge
```

```
 mdns-reflector-go -ifaces=en0,bridge100
2025/04/02 21:34:38 从命令行参数加载接口
2025/04/02 21:34:38 mDNS reflector started
```


```
ip a show en0 |grep -iE 'UP|inet '
15: en0: <UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 status UP
    inet 192.168.1.5/24 brd 192.168.1.255

ip a show bridge100 |grep -iE 'UP|inet '
32: bridge100: <UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 status UP
    inet 198.19.249.3/23 brd 198.19.249.255
```

compose.yml
```
cat compose.yml
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /path/ha.conf:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
```

```
cat ha.conf/configuration.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homekit:
  - name: HASS Bridge
    advertise_ip: "192.168.1.5"
    port: 21063
```
